name: Merge Template

on:
# schedule:
#   - cron: "0 4 * * *"
  workflow_dispatch:

env:
  TEMPLATE_REPO: "https://github.com/PyDrocsid/template.git"
  TEMPLATE_BRANCH: develop
  DEFAULT_BRANCH: develop

jobs:
  merge_template:
    name: Merge Template
    if: "false"
    runs-on: ubuntu-latest
    environment: merge-template
    concurrency: merge_template

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
          token: ${{ secrets.TOKEN }}

      - name: Merge Template
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          set -ex

          if [[ ${{ github.event_name }} = schedule ]]; then
            branch=$DEFAULT_BRANCH
          elif [[ ${{ github.ref_type }} != branch ]]; then
            echo "Can only update branches"
            exit 1
          else
            branch=${{ github.ref_name }}
          fi

          if [[ "$branch" = "template" ]]; then
            echo "Cannot update template branch"
            exit 1
          fi

          git remote add template ${TEMPLATE_REPO}
          git fetch template
          git checkout -b template template/${TEMPLATE_BRANCH}
          git push origin template || git push -f origin template

          if git merge-base --is-ancestor template $branch; then
            echo $branch is up to date
            exit 0
          fi

          echo Creating pull request from template into $branch
          gh -R ${{ github.repository }} pr create --title "Merge Template" --body "Merge template into $branch" --base $branch --head template || true
